//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquetes
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public int Precio { get; set; }
        public string Lugares { get; set; }
        public int CantDias { get; set; }
        public System.DateTime FechaViaje { get; set; }
        public bool Vigente { get; set; }
        public int CantCuotas { get; set; }
        public bool TipoMoneda { get; set; }
        public Nullable<int> ImpuestosF { get; set; }
        public Nullable<float> ImpuestosIVA { get; set; }
        public bool Visa { get; set; }
        public bool Internacional { get; set; }
    }
}
